name: Deploy Static Website

on:  
  push:
    branches:
      - develop

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4.1.1

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v4.0.2
  #       with:
  #         node-version: 18

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Build
  #       run: npm run build

  #     - name: Cache Dependencies
  #       uses: actions/cache@v4.0.2
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
      
  #     - name: Cache build output
  #       uses: actions/cache@v4.0.2
  #       with:
  #         path: dist
  #         key: ${{ runner.os }}-dist-${{ hashFiles('**/dist/**')}}

  deploy-dev:
    runs-on: ubuntu-latest
    # needs: build    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Debug files in repository
        run: |
          ls -la          
          pwd          

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET_DEV }} --delete --exclude ".git/*"
          echo "Deployment to DEV environment successfully completed"      